[package]
name = "cpio-deku"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["deku/std", "alloc"]
alloc = ["deku/alloc"]

[dependencies]
deku = { git = "https://github.com/sharksforarms/deku", branch = "impl-writer" }
